server:
  port: 8080

spring:
  mvc:
    format:
      date: yyyy-MM-dd
  datasource:
    url: jdbc:h2:file:./db/filmorate;DB_CLOSE_DELAY=-1;AUTO_RECONNECT=TRUE;MODE=PostgreSQL;
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
      continue-on-error: true

logging:
  level:
    org:
      zalando:
        logbook: TRACE
